name: 🚀🚀 Deploy Services
run-name: "Deploy Services: ${{ inputs.serviceName }} to ${{ inputs.envName }}"

on:
  workflow_call:
    inputs:
      envName:
        type: string
        required: true
      imageTag:
        type: string
        required: true
      serviceName:
        type: string
        default: (all)
  workflow_dispatch:
    inputs:
      envName:
        type: string
        required: true
      imageTag:
        description: (Optional) alternate build image tag
        type: string
        required: false
      serviceName:
        type: choice
        options:
          - (all)
          - admin
          - api
          - cloud-functions
          - cloudtasks
          - oracle
          - sql

# FIXME:
# If the event is a call, the environment name should be <envName>
# If the event is a dispatch, the environment name should be <user>.<envName>
# Functions and SQL should not be deployed in <user>.<envName> environments (yet)

jobs:
  CalculateImageTags:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: CalculateImageTags
        run: |
          if [ -n "${{ inputs.imageTag }}" ]; then
            echo "IMAGE_TAG_SHA=${{ inputs.imageTag }}"
            exit 0
          fi
          bash ./.github/scripts/CalculateImageTags.sh
        env:
          GCP_PROJECT: ${{ vars.GCP_PROJECT }}
          GCP_LOCATION: ${{ vars.GCP_LOCATION }}
          CURRENT_SHA: ${{ github.event.pull_request.head.sha || github.sha }}
          CURRENT_REF: ${{ github.head_ref || github.ref }}
    outputs:
      IMAGE_TAG_SHA: ${{ steps.CalculateImageTags.outputs.IMAGE_TAG_SHA }}
  AdminDeploy:
    needs: [CalculateImageTags]
    name: Deploy Admin service
    if: ${{ inputs.serviceName == 'admin' || inputs.serviceName == '(all)' }}
    uses: ./.github/workflows/deploy-svc-admin.yml
    secrets: inherit
    with:
      imageTag: ${{ needs.CalculateImageTags.outputs.IMAGE_TAG_SHA }}
      envName: ${{ inputs.envName }}
  ApiDeploy:
    needs: [CalculateImageTags]
    name: Deploy Api service
    if: ${{ inputs.serviceName == 'api' || inputs.serviceName == '(all)' }}
    uses: ./.github/workflows/deploy-svc-api.yml
    secrets: inherit
    with:
      imageTag: ${{ needs.CalculateImageTags.outputs.IMAGE_TAG_SHA }}
      envName: ${{ inputs.envName }}
  CloudFunctionsDeploy:
    needs: [CalculateImageTags]
    name: Deploy Cloud Functions
    if: ${{ inputs.serviceName == 'cloud-functions' || inputs.serviceName == '(all)' }}
    uses: ./.github/workflows/deploy-svc-cloud-functions.yml
    secrets: inherit
    with:
      imageTag: ${{ needs.CalculateImageTags.outputs.IMAGE_TAG_SHA }}
      envName: ${{ inputs.envName }}
  CloudTasksDeploy:
    needs: [CalculateImageTags]
    name: Deploy CloudTasks stacks
    if: ${{ inputs.serviceName == 'cloudtasks' || inputs.serviceName == '(all)' }}
    uses: ./.github/workflows/deploy-svc-cloudtasks.yml
    secrets: inherit
    with:
      imageTag: ${{ needs.CalculateImageTags.outputs.IMAGE_TAG_SHA }}
      envName: ${{ inputs.envName }}
  OracleDeploy:
    needs: [CalculateImageTags]
    name: Deploy Oracle service
    if: ${{ inputs.serviceName == 'oracle' || inputs.serviceName == '(all)' }}
    uses: ./.github/workflows/deploy-svc-oracle.yml
    secrets: inherit
    with:
      imageTag: ${{ needs.CalculateImageTags.outputs.IMAGE_TAG_SHA }}
      envName: ${{ inputs.envName }}
  SqlDeploy:
    needs: [CalculateImageTags]
    name: Deploy/migrate SQL
    if: ${{ inputs.serviceName == 'sql' || inputs.serviceName == '(all)' }}
    uses: ./.github/workflows/deploy-svc-sql.yml
    secrets: inherit
    with:
      imageTag: ${{ needs.CalculateImageTags.outputs.IMAGE_TAG_SHA }}
      envName: ${{ inputs.envName }}
