name: 🚀 Deploy Single Function
run-name: Deploy Function ${{ inputs.functionName }} to ${{ inputs.envName }}

on:
  workflow_dispatch:
    inputs:
      envName:
        description: "envName:\nNote: Functions are only deployed in shared environments"
        type: string
        required: true
      functionName:
        description: "functionName:\nsingle or comma,separated,list"
        type: string
        required: true
      imageTag:
        description: (Optional) alternate build image tag
        type: string
        required: false

jobs:
  CalculateImageTags:
    runs-on: ubuntu-latest
    environment: build
    steps:
      - uses: actions/checkout@v4
      - id: CalculateImageTags
        run: |
          if [ -n "${{ inputs.imageTag }}" ]; then
            echo "IMAGE_TAG_SHA=${{ inputs.imageTag }}"
            exit 0
          fi
          bash ./.github/scripts/CalculateImageTags.sh
        env:
          GCP_PROJECT: ${{ vars.GCP_PROJECT }}
          GCP_LOCATION: ${{ vars.GCP_LOCATION }}
          CURRENT_SHA: ${{ github.sha }}
          CURRENT_REF: ${{ github.head_ref || github.ref_name }}
    outputs:
      IMAGE_TAG_SHA: ${{ steps.CalculateImageTags.outputs.IMAGE_TAG_SHA }}
  CloudFunctionsDeploy:
    needs: [CalculateImageTags]
    uses: ./.github/workflows/deploy-svc-cloud-functions.yml
    secrets: inherit
    with:
      imageTag: ${{ needs.CalculateImageTags.outputs.IMAGE_TAG_SHA }}
      envName: ${{ inputs.envName }}
      functionName: ${{ inputs.functionName }}
