name: 🚀 Deploy Single Function
run-name: Deploy Function ${{ inputs.functionName }} to ${{ inputs.envName }}

on:
  workflow_dispatch:
    inputs:
      envName:
        description: "envName:\nNote: Functions are only deployed in shared environments"
        type: string
        required: true
      functionName:
        description: "functionName:\nsingle or comma,separated,list"
        type: string
        required: true

jobs:
  CalculateImageTags:
    runs-on: ubuntu-latest
    steps:
      - id: CalculateImageTags
        run: ./.github/scripts/CalculateImageTags.sh
        env:
          GCP_PROJECT: ${{ vars.GCP_PROJECT }}
          GCP_LOCATION: ${{ vars.GCP_LOCATION }}
          CURRENT_SHA: ${{ github.event.pull_request.head.sha || github.sha }}
          CURRENT_REF: ${{ github.head_ref || github.ref }}
    outputs:
      IMAGE_TAG_SHA: ${{ steps.CalculateImageTags.outputs.IMAGE_TAG_SHA }}
  CloudFunctionsDeploy:
    needs: [CalculateImageTags]
    uses: ./.github/workflows/deploy-svc-cloud-functions.yml
    secrets: inherit
    with:
      imageTag: ${{ needs.CalculateImageTags.outputs.IMAGE_TAG_SHA }}
      envName: ${{ inputs.envName }}
      functionName: ${{ inputs.functionName }}
