name: 🔄 On Push to Main
run-name: "Deploy main to dev"

on:
  push:
    branches: [main]

jobs:
  UnitTests:
    uses: ./.github/workflows/UnitTest.yml
    secrets: inherit
  DeployToDev:
    needs: [UnitTests]
    uses: ./.github/workflows/_do-deploy-env.yml
    secrets: inherit
    with:
      envName: dev
