name: 🔄 On Push to Main
run-name: "Deploy main to dev"

on:
  push:
    branches: [main]

jobs:
  Build:
    uses: ./.github/workflows/Build.yml
    secrets: inherit
  UnitTests:
    needs: [Build]
    uses: ./.github/workflows/UnitTest.yml
    with:
      imageTag: ${{ needs.Build.outputs.IMAGE_TAG_SHA }}
    secrets: inherit
  DeployToDev:
    needs: [Build, UnitTests]
    uses: ./.github/workflows/_do-deploy-env.yml
    secrets: inherit
    with:
      envName: dev
      imageTag: ${{ needs.Build.outputs.IMAGE_TAG_SHA }}
