name: 🔄 On Pull Request
run-name: "Pull request #${{ github.event.pull_request.number }} updated"

on:
  pull_request:

jobs:
  EnsureBuild:
    uses: ./.github/workflows/Build.yml
    secrets: inherit
  Test:
    needs: [EnsureBuild]
    uses: ./.github/workflows/UnitTest.yml
    secrets: inherit
    with:
      imageTag: ${{ needs.EnsureBuild.outputs.IMAGE_TAG_SHA }}
# FIXME: add preview-cloudtasks-dev/-prod
# FIXME: add preview-cloudsql-dev/-prod
