name: ⚙️ Build

on:
  workflow_call:
    secrets:
      GCP_PRIVATE_KEY_JSON:

jobs:
  Build:
    concurrency:
      group: Build-${{ github.ref }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    environment: build
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - run: |
          # Build image for ${{ github.sha }}
          # FIXME: add tag for dev/release
          docker build -t ${{ vars.GCP_LOCATION }}-docker.pkg.dev/${{ vars.GCP_PROJECT }}/builds/build:git-${{ github.sha }} .
      - uses: "google-github-actions/auth@v2"
        with:
          project_id: "${{ vars.GCP_PROJECT }}"
          credentials_json: "${{ secrets.GCP_PRIVATE_KEY_JSON }}"
      - run: |
          # Push image for ${{ github.sha }}
          gcloud auth configure-docker ${{ vars.GCP_LOCATION }}-docker.pkg.dev
          docker push ${{ vars.GCP_LOCATION }}-docker.pkg.dev/${{ vars.GCP_PROJECT }}/builds/build:git-${{ github.sha }}
