name: Build
run-name: "[Build] ${{ github.ref_name }} @ ${{ github.sha }}"

on:
  workflow_call:

jobs:
  Build:
    concurrency:
      group: Build-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Building code"
      - run: echo "Pushing image"
      - run: echo "Pushing statistics"
