name: ⚙️ Build

on:
  workflow_call:

jobs:
  Build:
    concurrency:
      group: Build-${{ github.ref }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    environment: build
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - run: |
          echo "Building image for ${{ github.sha }}"
          # Note: To implement `nx affected` here we would need to check out
          #       the full repo (we only have on commit by default) and also
          #       copy it through the Docker build context. Because our repo
          #       is very large these two steps will take a while, meaning
          #       `affected` may not be very useful in our CI builds.
          # FIXME: also tag for dev/release
          pwd
          ls -al ${{ github.workspace }}
          git log
          docker build -t ${{ vars.GCP_LOCATION }}-docker.pkg.dev/${{ vars.GCP_PROJECT }}/builds/build:${{ github.sha }} .
      - uses: "google-github-actions/auth@v2"
        with:
          project_id: "${{ vars.GCP_PROJECT }}"
          credentials_json: "${{ secrets.GITHUB_PRIVATE_KEY_JSON }}"
      - run: |
          echo "Pushing image for ${{ github.sha }}"
          docker push -t ${{ vars.GCP_LOCATION }}-docker.pkg.dev/${{ vars.GCP_PROJECT }}/builds/build:${{ github.sha }}
