name: ⚙️ Build and Tag Image

on:
  workflow_call:
    outputs:
      IMAGE_TAG_SHA:
        value: ${{ jobs.CalculateImageTags.outputs.IMAGE_TAG_SHA }}
      IMAGE_TAG_REF:
        value: ${{ jobs.CalculateImageTags.outputs.IMAGE_TAG_REF }}

concurrency:
  group: build-${{ github.head_ref || github.ref_name }}

jobs:
  CalculateImageTags:
    uses: ./.github/workflows/CalculateImageTags.yml
  Build:
    needs: [CalculateImageTags]
    environment: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - uses: "google-github-actions/auth@v2"
        with:
          project_id: "${{ vars.GCP_PROJECT }}"
          credentials_json: "${{ secrets.GCP_PRIVATE_KEY_JSON }}"
      - run: |
          # Build image for ${{ github.head_ref || github.ref_name }} (if needed)
          IMAGE_TAG_SHA="${{ needs.CalculateImageTags.outputs.IMAGE_TAG_SHA }}"
          IMAGE_TAG_REF="${{ needs.CalculateImageTags.outputs.IMAGE_TAG_REF }}"
          gcloud auth configure-docker ${{ vars.GCP_LOCATION }}-docker.pkg.dev --quiet

          # Check for existing image
          if docker manifest inspect "${IMAGE_TAG_SHA}" >/dev/null; then
            echo Found image "${IMAGE_TAG_SHA}"
            echo Image already exists, skipping build
            exit 0
          fi

          # Build image
          docker build \
            -t "${IMAGE_TAG_SHA}" \
            -t "${IMAGE_TAG_REF}" \
            .

          # Push image and tags
          docker push "${IMAGE_TAG_SHA}"
          docker push "${IMAGE_TAG_REF}"
