name: 📚 Build

on:
  workflow_call:

jobs:
  Build:
    name: Build-${{ github.ref }}@${{ github.sha }}
    concurrency:
      group: Build-${{ github.ref }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
      - run: echo "Building code"
      - run: echo "Pushing image"
      - run: echo "Pushing statistics"
