name: ⚙️ Build

on:
  workflow_call:
    secrets:
      GCP_PRIVATE_KEY_JSON:

jobs:
  CalculateImageTags:
    uses: ./.github/workflows/CalculateImageTags.yml
  Build:
    needs: [CalculateImageTags]
    concurrency:
      group: Build-${{ github.ref }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    environment: build
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - run: |
          # Build image for ${{ github.sha }}
          docker build \
            -t ${{ needs.CalculateImageTags.outputs.image-tag-sha }} \
            -t ${{ needs.CalculateImageTags.outputs.image-tag-ref }} \
            .
      - uses: "google-github-actions/auth@v2"
        with:
          project_id: "${{ vars.GCP_PROJECT }}"
          credentials_json: "${{ secrets.GCP_PRIVATE_KEY_JSON }}"
      - run: |
          # Push image for ${{ github.sha }}
          gcloud auth configure-docker ${{ vars.GCP_LOCATION }}-docker.pkg.dev
          docker push \
            ${{ needs.CalculateImageTags.outputs.image-tag-sha }} \
            ${{ needs.CalculateImageTags.outputs.image-tag-ref }}
