name: "Task: Build and Tag Image"

on:
  workflow_call:
    outputs:
      IMAGE_TAG_SHA:
        value: ${{ jobs.Build.outputs.IMAGE_TAG_SHA }}
      IMAGE_TAG_REF:
        value: ${{ jobs.Build.outputs.IMAGE_TAG_REF }}

concurrency:
  group: build-${{ github.head_ref || github.ref_name }}

jobs:
  Build:
    environment: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - id: CalculateImageTags
        run: ./.github/scripts/CalculateImageTags.sh
        env:
          GCP_PROJECT: ${{ vars.GCP_PROJECT }}
          GCP_LOCATION: ${{ vars.GCP_LOCATION }}
          CURRENT_SHA: ${{ github.event.pull_request.head.sha || github.sha }}
          CURRENT_REF: ${{ github.head_ref || github.ref_name }}
      - uses: "google-github-actions/auth@v2"
        with:
          project_id: "${{ vars.GCP_PROJECT }}"
          credentials_json: "${{ secrets.GCP_PRIVATE_KEY_JSON }}"
      - run: |
          # Build image for ${{ github.head_ref || github.ref_name }} (if needed)

          IMAGE_TAG_SHA="${{ steps.CalculateImageTags.outputs.IMAGE_TAG_SHA }}"
          IMAGE_TAG_REF="${{ steps.CalculateImageTags.outputs.IMAGE_TAG_REF }}"
          gcloud auth configure-docker ${{ vars.GCP_LOCATION }}-docker.pkg.dev --quiet

          # Check for existing image
          if docker manifest inspect "${IMAGE_TAG_SHA}" >/dev/null; then
            echo Found image "${IMAGE_TAG_SHA}"
            echo Image already exists, skipping build
            exit 0
          fi

          # Build image
          docker build \
            --build-arg "FONTAWESOME_TOKEN=${{ secrets.FONTAWESOME_TOKEN }}" \
            --build-arg "MOBISCROLL_TOKEN=${{ secrets.MOBISCROLL_TOKEN }}" \
            -t "${IMAGE_TAG_SHA}" \
            -t "${IMAGE_TAG_REF}" \
            .

          # Push image and tags
          docker push "${IMAGE_TAG_SHA}"
          docker push "${IMAGE_TAG_REF}"
    outputs:
      IMAGE_TAG_SHA: ${{ steps.CalculateImageTags.outputs.IMAGE_TAG_SHA }}
      IMAGE_TAG_REF: ${{ steps.CalculateImageTags.outputs.IMAGE_TAG_REF }}
