name: ⚙️ Calculate Image Tags

on:
  workflow_call:
    outputs:
      image-tag-sha:
        description: Tag using git commit SHA
        value: ${{ jobs.CalculateImageTags.outputs.IMAGE_TAG_SHA}}
      image-tag-ref:
        description: Tag using current ref (branch/tag)
        value: ${{ jobs.CalculateImageTags.outputs.IMAGE_TAG_REF}}
      # image-tag-release:
      #   description: Tag using current release/version
      #   value: ${{ jobs.CalculateImageTags.outputs.IMAGE_TAG_RELEASE }}

jobs:
  CalculateImageTags:
    concurrency:
      group: GetBuildImage-${{ github.ref }}
    runs-on: ubuntu-latest
    environment: build
    outputs:
      IMAGE_TAG_SHA: ${{ steps.pullImage.outputs.IMAGE_TAG_SHA }}
      IMAGE_TAG_REF: ${{ steps.pullImage.outputs.IMAGE_TAG_REF }}
      # IMAGE_TAG_RELEASE: ${{ steps.pullImage.outputs.IMAGE_TAG_RELEASE }}
    steps:
      - id: pullImage
        run: |
          # Calculate image tags
          TARGET_REPO="${{ vars.GCP_LOCATION }}-docker.pkg.dev/${{ vars.GCP_PROJECT }}/builds/build"

          CURRENT_SHA="${{ github.event.pull_request.head.sha || github.sha }}"
          echo "IMAGE_TAG_SHA=${TARGET_REPO}:git-${CURRENT_SHA}" >>"$GITHUB_OUTPUT"

          CURRENT_REF="${{ github.ref }}"
          REF_TAG="${CURRENT_REF//\//_}" # refs/head/fix/foo -> refs_heads_fix_foo
          echo "IMAGE_TAG_REF=${TARGET_REPO}:ref-${CURRENT_REF}" >>"$GITHUB_OUTPUT"

          # FIXME: tag the dev build/prod release version
          # CURRENT_RELEASE="${ ??? }"
          # echo "IMAGE_TAG_RELEASE=${TARGET_REPO}:v${CURRENT_RELEASE}" >>"$GITHUB_OUTPUT"
