name: ⚙️ Calculate Image Tags

on:
  workflow_call:
    outputs:
      IMAGE_TAG_SHA:
        description: Image tag based on git SHA
        value: ${{ jobs.CalculateImageTags.outputs.IMAGE_TAG_SHA }}
      IMAGE_TAG_REF:
        description: Image tag based on git ref
        value: ${{ jobs.CalculateImageTags.outputs.IMAGE_TAG_REF }}

jobs:
  CalculateImageTags:
    runs-on: ubuntu-latest
    environment: build
    steps:
      - uses: actions/checkout@v4
      - id: CalculateImageTags
        env:
          GCP_PROJECT: ${{ vars.GCP_PROJECT }}
          GCP_LOCATION: ${{ vars.GCP_LOCATION }}
          CURRENT_SHA: ${{ github.event.pull_request.head.sha || github.sha }}
          CURRENT_REF: ${{ github.head_ref || github.ref }}
        run: |
          # Calculate image tags for the current job

          # INPUTS: Define these environment variables:
          # - GCP_LOCATION: e.g. us-central1
          # - GCP_PROJECT: e.g. bicycle-health-dev
          # - CURRENT_SHA: e.g. github.event.pull_request.head.sha || github.sha
          # - CURRENT_REF: e.g. github.head_ref || github.ref

          OK=yes
          [ -z "${GCP_LOCATION}" ] && echo "Error: missing GCP_LOCATION" && OK=no
          [ -z "${GCP_PROJECT}" ] && echo "Error: missing GCP_PROJECT" && OK=no
          [ -z "${CURRENT_SHA}" ] && echo "Error: missing CURRENT_SHA" && OK=no
          [ -z "${CURRENT_REF}" ] && echo "Error: missing CURRENT_REF" && OK=no
          [[ "${OK}" == "no" ]] && exit 1

          TARGET_REPO="${GCP_LOCATION}-docker.pkg.dev/${GCP_PROJECT}/builds/build"

          # OUTPUT: IMAGE_TAG_SHA 
          echo "IMAGE_TAG_SHA=${TARGET_REPO}:git-${CURRENT_SHA}" >>"$GITHUB_OUTPUT"

          # OUTPUT: IMAGE_TAG_REF
          REF_TAG="${CURRENT_REF//\//_}" # refs/head/fix/foo -> refs_heads_fix_foo
          echo "IMAGE_TAG_REF=${TARGET_REPO}:ref-${REF_TAG}" >>"$GITHUB_OUTPUT"

          # FIXME: tag the dev build/prod release version
          # CURRENT_RELEASE="${ ??? }"
          # echo "IMAGE_TAG_RELEASE=${TARGET_REPO}:v${CURRENT_RELEASE}" >>"$GITHUB_OUTPUT"
    outputs:
      IMAGE_TAG_SHA: ${{ steps.CalculateImageTags.outputs.IMAGE_TAG_SHA }}
      IMAGE_TAG_REF: ${{ steps.CalculateImageTags.outputs.IMAGE_TAG_REF }}
