name: ⚙️ Cloud Run Deployment

on:
  workflow_call:
    inputs:
      imageTag:
        type: string
        required: true
      serviceName:
        type: string
        required: true
      envName:
        type: string
        required: true

jobs:
  CloudRunServiceDeployment:
    name: Deploy ${{ inputs.serviceName }}→${{ inputs.envName }} (Cloud Run Service)
    environment: ${{ inputs.envName }}
    concurrency:
      group: CloudRunServiceDeployment-${{ inputs.serviceName }}-${{ inputs.envName }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            ./.github/scripts/calculateImageTags.sh
      - uses: "google-github-actions/auth@v2"
        with:
          project_id: "${{ vars.GCP_PROJECT }}"
          credentials_json: "${{ secrets.GCP_PRIVATE_KEY_JSON }}"
      - run: |
          # Deploy Run Service: ${{ inputs.serviceName }}-${{ inputs.envName }}
          gcloud run deploy ${{ inputs.serviceName }}-${{ inputs.envName }} \
            --image ${{ inputs.imageTag }} \
            --command "pnpm start ${{ inputs.serviceName }}-${{ inputs.envName }}"
