name: Cloud Function Deployment
run-name: "Cloud Function Deployment | ${{ inputs.functionName }} in ${{ inputs.envName }}"

on:
  workflow_call:
    inputs:
      functionName:
        type: string
        required: false
        default: ALL_FUNCTIONS
      envName:
        type: string
        required: true

jobs:
  CloudFunctionDeployment:
    environment: ${{ inputs.envName }}
    concurrency:
      group: CloudFunctionDeployment-${{ inputs.functionName }}
    runs-on: ubuntu-latest
    steps:
      - if: ${{ inputs.functionName == 'ALL_FUNCTIONS' }}
        run: |
          echo: "Deploy ALL Cloud Functions for ${{ inputs.envName }}"
      - if: ${{ inputs.functionName != 'ALL_FUNCTIONS' }}
        run: |
          echo "Deploy Cloud Function in ${{ inputs.envName }}: ${{ inputs.functionName }}"
