name: Cloud Run Deployment
run-name: "Cloud Run Deployment | ${{ inputs.serviceName }} in ${{ inputs.envName }}"

on:
  workflow_call:
    inputs:
      serviceName:
        type: string
        required: true
      envName:
        type: string
        required: true

jobs:
  CloudRunServiceDeployment:
    name: CloudRunServiceDeployment-${{ inputs.serviceName }}→${{ inputs.envName }}
    environment: ${{ inputs.envName }}
    concurrency:
      group: CloudRunServiceDeployment-${{ inputs.serviceName }}-${{ inputs.envName }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Deploy Run Service: ${{ inputs.serviceName }}"
