name: ⚙️ Cloud Run Deployment

on:
  workflow_call:
    inputs:
      serviceName:
        type: string
        required: true
      envName:
        type: string
        required: true

jobs:
  CloudRunServiceDeployment:
    name: Deploy ${{ inputs.serviceName }}→${{ inputs.envName }} (Cloud Run Service)
    environment: ${{ inputs.envName }}
    concurrency:
      group: CloudRunServiceDeployment-${{ inputs.serviceName }}-${{ inputs.envName }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            ./.github/scripts/calculateImageTags.sh
          sparse-checkout-cone-mode: false
      - id: CalculateImageTags
        run: bash -ue ./.github/scripts/calculateImageTags.sh
        env:
          GCP_PROJECT: ${{ vars.GCP_PROJECT }}
          GCP_LOCATION: ${{ vars.GCP_LOCATION }}
          CURRENT_SHA: ${{ github.event.pull_request.head.sha || github.sha }}
          CURRENT_REF: ${{ github.head_ref || github.ref }}
      - uses: "google-github-actions/auth@v2"
        with:
          project_id: "${{ vars.GCP_PROJECT }}"
          credentials_json: "${{ secrets.GCP_PRIVATE_KEY_JSON }}"
      - run: |
          # Deploy Run Service: ${{ inputs.serviceName }}-${{ inputs.envName }}
          gcloud run deploy ${{ inputs.serviceName }}-${{ inputs.envName }} \
            --image ${{ steps.CalculateImageTags.outputs.IMAGE_TAG_SHA }} \
            --command "pnpm start ${{ inputs.serviceName }}-${{ inputs.envName }}"
