name: ⚙️ Cloud Function Deployment

on:
  workflow_call:
    inputs:
      imageTag:
        type: string
        required: true
      envName:
        type: string
        required: true
      functionName:
        type: string
        required: false
        default: ALL_FUNCTIONS

jobs:
  CloudFunctionDeployment:
    name: Deploy ${{ inputs.functionName }}→${{ inputs.envName }} (Cloud Functions)
    environment: ${{ inputs.envName }}
    concurrency:
      group: CloudFunctionDeployment-${{ inputs.envName }}
    runs-on: ubuntu-latest
    steps:
      - uses: "google-github-actions/auth@v2"
        with:
          project_id: "${{ vars.GCP_PROJECT }}"
          credentials_json: "${{ secrets.GCP_PRIVATE_KEY_JSON }}"
      - run: |
          # Deploy Cloud Functions from build image
          IMG_TAG="${{ inputs.imageTag }}"
          FUNCTIONS="${{ inputs.functionName }}"
          IMG_LOCATION="${IMG_TAG%%-docker.pkg.dev/*}"
          gcloud auth configure-docker "${IMG_LOCATION}-docker.pkg.dev" --quiet
          # FIXME: container needs google creds passed in
          if [[ "${FUNCTIONS}" == "ALL_FUNCTIONS" ]]; then
            docker run ${IMG_TAG:-ImageNotSpecifiedError} pnpm functions:deploy
          else
            docker run ${IMG_TAG:-ImageNotSpecifiedError} pnpm functions:deploy "${FUNCTIONS}"
          fi
