name: Cloud Run Deployment

on:
  workflow_call:
    inputs:
      serviceName:
        type: string
        required: true

jobs:
  doTest:
    uses: ./.github/workflows/Test.yml
  deployCloudRunService:
    needs: [doTest]
    runs-on: ubuntu
    concurrency:
      group: deploy-cloud-run-${{ inputs.serviceName }}
    steps:
      - run: |
          echo "Deploy Run Service: ${{ inputs.serviceName }}"
