name: Cloud Run Deployment

on:
  workflow_call:
    inputs:
      serviceName:
        type: string
        required: true

jobs:
  CloudRunServiceDeployment:
    concurrency:
      group: CloudRunServiceDeployment-${{ inputs.serviceName }}
    runs-on: ubuntu
    steps:
      - run: |
          echo "Deploy Run Service: ${{ inputs.serviceName }}"
