name: ⚙️ Cloud Function Deployment

on:
  workflow_call:
    inputs:
      envName:
        type: string
        required: true
      functionName:
        type: string
        required: false
        default: ALL_FUNCTIONS

jobs:
  CloudFunctionDeployment:
    name: Deploy ${{ inputs.functionName }}→${{ inputs.envName }} (Cloud Functions)
    environment: ${{ inputs.envName }}
    concurrency:
      group: CloudFunctionDeployment-${{ inputs.envName }}
    runs-on: ubuntu-latest
    steps:
      - id: CalculateImageTags
        run: bash ./.github/scripts/calculateImageTags.sh
      - uses: "google-github-actions/auth@v2"
        with:
          project_id: "${{ vars.GCP_PROJECT }}"
          credentials_json: "${{ secrets.GCP_PRIVATE_KEY_JSON }}"
      - run: |
          IMAGE="${{ steps.CalculateImageTags.outputs.IMAGE_TAG_SHA }}"
          FUNCTIONS="${{ inputs.functionName }}"
          # FIXME: container needs google creds passed in
          if [[ "${FUNCTIONS}" == "ALL_FUNCTIONS" ]]; then
            docker run ${IMAGE:-ImageNotSpecifiedError} pnpm functions:deploy
          else
            docker run ${IMAGE:-ImageNotSpecifiedError} pnpm functions:deploy "${FUNCTIONS}"
          fi
