name: Cloud Run Deployment

on:
  workflow_call:
    inputs:
      serviceName:
        type: string
        required: true

jobs:
  deployCloudRunService:
    runs-on: ubuntu
    concurrency:
      group: deploy-cloud-run-${{ inputs.serviceName }}
    steps:
      - uses: ./Test.yml
      - run: |
          echo "Deploy Run Service: ${{ inputs.serviceName }}"
