name: Cloud Function Deployment

on:
  workflow_call:
    inputs:
      functionName:
        type: string
        required: false
        default: ALL_FUNCTIONS

jobs:
  doTest:
    uses: ./.github/workflows/Test.yml
  deployCloudFunction:
    needs: [doTest]
    runs-on: ubuntu-latest
    concurrency:
      group: deploy-function-${{ inputs.functionName }}
    steps:
      - if: ${{ inputs.functionName == 'ALL_FUNCTIONS' }}
        run: |
          echo: "Deploy ALL Cloud Functions"
      - if: ${{ inputs.functionName != 'ALL_FUNCTIONS' }}
        run: |
          echo "Deploy Cloud Function: ${{ inputs.functionName }}"
