name: Cloud Function Deployment

on:
  workflow_call:
    inputs:
      functionName:
        type: string
        required: false
        default: ALL_FUNCTIONS
      envName:
        type: string
        required: true

jobs:
  CloudFunctionDeployment:
    name: CloudFunctionDeployment-${{ inputs.functionName }}→${{ inputs.envName }}
    environment: ${{ inputs.envName }}
    concurrency:
      group: CloudFunctionDeployment-${{ inputs.functionName }}-${{ inputs.envName }}
    runs-on: ubuntu-latest
    steps:
      - if: ${{ inputs.functionName == 'ALL_FUNCTIONS' }}
        run: |
          echo "Deploy ALL Cloud Functions for ${{ inputs.envName }}"
      - if: ${{ inputs.functionName != 'ALL_FUNCTIONS' }}
        run: |
          echo "Deploy Cloud Function ${{ inputs.envName }} in ${{ inputs.functionName }}"
