name: Cloud Function Deployment

on:
  workflow_call:
    inputs:
      functionName:
        type: string
        required: false
        default: ALL_FUNCTIONS

jobs:
  CloudFunctionDeployment:
    concurrency:
      group: CloudFunctionDeployment-${{ inputs.functionName }}
    runs-on: ubuntu-latest
    steps:
      - if: ${{ inputs.functionName == 'ALL_FUNCTIONS' }}
        run: |
          echo: "Deploy ALL Cloud Functions"
      - if: ${{ inputs.functionName != 'ALL_FUNCTIONS' }}
        run: |
          echo "Deploy Cloud Function: ${{ inputs.functionName }}"
