name: "📚 Deploy service: API"
run-name: Deploy API to ${{ inputs.envName }}

on:
  workflow_call:
    inputs:
      envName:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      envName:
        required: true
        type: string

jobs:
  EnsureBuild:
    uses: ./.github/workflows/Build.yml
    secrets: inherit
  DeployApiService:
    needs: [EnsureBuild]
    uses: ./.github/workflows/CloudRunServiceDeployment.yml
    secrets: inherit
    with:
      serviceName: api-${{ inputs.envName }}
      envName: ${{ inputs.envName }}
  DeployApiInfra:
    needs: [EnsureBuild]
    uses: ./.github/workflows/InfraStackDeployment.yml
    secrets: inherit
    with:
      envName: ${{ inputs.envName }}
      serviceName: api-${{ inputs.envName }}
