name: "📚 Deploy service: SQL"
run-name: Deploy SQL to ${{ inputs.envName }}

on:
  workflow_call:
    inputs:
      envName:
        required: true
        type: string

jobs:
  DeploySQL:
    uses: ./.github/workflows/InfraStackDeployment.yml
    with:
      serviceName: sql-${{ inputs.envName }}
      envName: ${{ inputs.envName }}
  SqlMigration:
    needs: [DeploySQL]
    uses: ./.github/workflows/SqlMigration.yml
    with:
      envName: ${{ inputs.envName }}
