name: "📚 Deploy service: Cloud Functions"
run-name: Deploy Cloud Function(s) to ${{ inputs.envName }}

on:
  workflow_call:
    inputs:
      envName:
        required: true
        type: string
      functionName:
        type: string
        required: false
        default: ALL_FUNCTIONS

jobs:
  EnsureBuild:
    uses: ./.github/workflows/Build.yml
    secrets: inherit
  DeployCloudFunctions:
    needs: [EnsureBuild]
    uses: ./.github/workflows/CloudFunctionDeployment.yml
    secrets: inherit
    with:
      envName: ${{ inputs.envName }}
      functionName: ${{ inputs.functionName }}
