name: Deploy CloudTasks
run-name: Deploy CloudTask queues to ${{ inputs.envName }}

on:
  workflow_call:
    inputs:
      envName:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      envName:
        required: true
        type: choice
        options:
          - dev
          # - prod

jobs:
  DeployCloudTasks:
    uses: ./.github/workflows/PulumiStackDeployment.yml
    with:
      stackName: cloudtasks-${{ inputs.envName }}
      envName: ${{ inputs.envName }}
