name: "📚 Deploy service: CloudTasks"
run-name: Deploy CloudTask queues to ${{ inputs.envName }}

on:
  workflow_call:
    inputs:
      imageTag:
        type: string
        required: true
      envName:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      envName:
        required: true
        type: choice
        options: [dev]

jobs:
  DeployCloudTasks:
    uses: ./.github/workflows/InfraStackDeployment.yml
    secrets: inherit
    with:
      imageTag: ${{ inputs.imageTag }}
      serviceName: cloudtasks-${{ inputs.envName }}
      envName: ${{ inputs.envName }}
