name: "📚 Deploy service: CloudTasks"
run-name: Deploy CloudTask queues to ${{ inputs.envName }}

on:
  workflow_call:
    inputs:
      envName:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      envName:
        required: true
        type: choice
        options: [dev]

jobs:
  EnsureBuild:
    uses: ./.github/workflows/Build.yml
    secrets: inherit
  DeployCloudTasks:
    needs: [EnsureBuild]
    uses: ./.github/workflows/InfraStackDeployment.yml
    secrets: inherit
    with:
      serviceName: cloudtasks-${{ inputs.envName }}
      envName: ${{ inputs.envName }}
