name: "📚 Deploy service: API"
run-name: Deploy API to ${{ inputs.envName }}

on:
  workflow_call:
    inputs:
      imageTag:
        type: string
        required: true
      envName:
        required: true
        type: string

jobs:
  DeployApiService:
    uses: ./.github/workflows/CloudRunServiceDeployment.yml
    secrets: inherit
    with:
      imageTag: ${{ inputs.imageTag }}
      envName: ${{ inputs.envName }}
      serviceName: api
  DeployApiInfra:
    uses: ./.github/workflows/InfraStackDeployment.yml
    secrets: inherit
    with:
      imageTag: ${{ inputs.imageTag }}
      envName: ${{ inputs.envName }}
      serviceName: api
