name: "Deploy service: Cloud Functions"
run-name: Deploy Cloud Function(s) to ${{ inputs.envName }}

on:
  workflow_call:
    inputs:
      imageTag:
        type: string
        required: true
      envName:
        required: true
        type: string
      functionName:
        type: string
        required: false
        default: ALL_FUNCTIONS

jobs:
  DeployCloudFunctions:
    uses: ./.github/workflows/CloudFunctionDeployment.yml
    secrets: inherit
    with:
      imageTag: ${{ inputs.imageTag }}
      envName: ${{ inputs.envName }}
      functionName: ${{ inputs.functionName }}
