name: 🚀 Deploy Single Function
run-name: Deploy Function ${{ inputs.functionName }} to ${{ inputs.envName }}

on:
  workflow_dispatch:
    inputs:
      envName:
        description: "envName:\nNote: Functions are only deployed in shared environments"
        type: string
        required: true
      functionName:
        description: "functionName:\nsingle or comma,separated,list"
        type: string
        required: true

# Note: The first two jobs have the same concurrency group as Build. This
# ensures that the other jobs are queued after the actual Build job.
# (Build -> EnsureBuild) -> CalculateImageTags -> <others>
# (EnsureBuild -> Build) -> CalculateImageTags -> <others>
jobs:
  EnsureBuild:
    # see note above
    concurrency:
      group: build-${{ github.head_ref || github.ref_name }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo Concurrency group: build-${{ github.head_ref || github.ref_name }}
          # Ensure build has been queued
          sleep 20
  CalculateImageTags:
    needs: [EnsureBuild]
    environment: build
    runs-on: ubuntu-latest
    # see note above
    concurrency:
      group: build-${{ github.head_ref || github.ref_name }}
    steps:
      - uses: actions/checkout@v4
      - id: CalculateImageTags
        uses: ./.github/actions/CalculateImageTags
        with:
          gcp_project: ${{ vars.GCP_PROJECT }}
          gcp_location: ${{ vars.GCP_LOCATION }}
          sha: ${{ github.sha }}
          ref: ${{ github.ref_name }}
    outputs:
      IMAGE_TAG_SHA: ${{ steps.CalculateImageTags.outputs.IMAGE_TAG_SHA }}
      IMAGE_TAG_REF: ${{ steps.CalculateImageTags.outputs.IMAGE_TAG_REF }}
  CloudFunctionsDeploy:
    needs: [CalculateImageTags]
    uses: ./.github/workflows/deploy-svc-cloud-functions.yml
    secrets: inherit
    with:
      imageTag: ${{ needs.CalculateImageTags.outputs.IMAGE_TAG_SHA }}
      envName: ${{ inputs.envName }}
      functionName: ${{ inputs.functionName }}
