name: 🚀 Deploy Single Function
run-name: Deploy Function ${{ inputs.functionName }} to ${{ inputs.envName }}

on:
  workflow_dispatch:
    inputs:
      imageTag:
        type: string
        required: true
      envName:
        description: "envName:\nNote: Functions are only deployed in shared environments"
        type: string
        required: true
      functionName:
        description: "functionName:\nsingle or comma,separated,list"
        type: string
        required: true

jobs:
  CloudFunctionsDeploy:
    uses: ./.github/workflows/deploy-svc-cloud-functions.yml
    with:
      imageTag: ${{ inputs.imageTag }}
      envName: ${{ inputs.envName }}
      functionName: ${{ inputs.functionName }}
