name: 🚀🚀 Deploy Services
run-name: "Deploy Services: ${{ inputs.serviceName }} to ${{ inputs.envName }}"

on:
  workflow_call:
    inputs:
      envName:
        type: string
        required: true
      serviceName:
        type: string
        default: (all)
  workflow_dispatch:
    inputs:
      envName:
        type: string
        required: true
      serviceName:
        type: choice
        options:
          - (all)
          - admin
          - api
          - cloud-functions
          - cloudtasks
          - oracle
          - sql

# FIXME:
# If the event is a call, the environment name should be <envName>
# If the event is a dispatch, the environment name should be <user>.<envName>
# Functions and SQL should not be deployed in <user>.<envName> environments (yet)

jobs:
  EnsureBuild:
    uses: ./.github/workflows/Build.yml
  CalculateImageTags:
    uses: ./.github/workflows/CalculateImageTags.yml
  AdminDeploy:
    name: Deploy Admin service
    needs: [EnsureBuild, CalculateImageTags]
    if: ${{ inputs.serviceName == 'admin' || inputs.serviceName == '(all)' }}
    uses: ./.github/workflows/deploy-svc-admin.yml
    secrets: inherit
    with:
      imageTag: ${{ needs.CalculateImageTags.outputs.IMAGE_TAG_SHA }}
      envName: ${{ inputs.envName }}
  ApiDeploy:
    name: Deploy Api service
    needs: [CalculateImageTags]
    if: ${{ inputs.serviceName == 'api' || inputs.serviceName == '(all)' }}
    uses: ./.github/workflows/deploy-svc-api.yml
    secrets: inherit
    with:
      imageTag: ${{ needs.CalculateImageTags.outputs.IMAGE_TAG_SHA }}
      envName: ${{ inputs.envName }}
  CloudFunctionsDeploy:
    name: Deploy Cloud Functions
    needs: [CalculateImageTags]
    if: ${{ inputs.serviceName == 'cloud-functions' || inputs.serviceName == '(all)' }}
    uses: ./.github/workflows/deploy-svc-cloud-functions.yml
    secrets: inherit
    with:
      imageTag: ${{ needs.CalculateImageTags.outputs.IMAGE_TAG_SHA }}
      envName: ${{ inputs.envName }}
  CloudTasksDeploy:
    name: Deploy CloudTasks stacks
    needs: [CalculateImageTags]
    if: ${{ inputs.serviceName == 'cloudtasks' || inputs.serviceName == '(all)' }}
    uses: ./.github/workflows/deploy-svc-cloudtasks.yml
    secrets: inherit
    with:
      imageTag: ${{ needs.CalculateImageTags.outputs.IMAGE_TAG_SHA }}
      envName: ${{ inputs.envName }}
  OracleDeploy:
    name: Deploy Oracle service
    needs: [CalculateImageTags]
    if: ${{ inputs.serviceName == 'oracle' || inputs.serviceName == '(all)' }}
    uses: ./.github/workflows/deploy-svc-oracle.yml
    secrets: inherit
    with:
      imageTag: ${{ needs.CalculateImageTags.outputs.IMAGE_TAG_SHA }}
      envName: ${{ inputs.envName }}
  SqlDeploy:
    name: Deploy/migrate SQL
    needs: [CalculateImageTags]
    if: ${{ inputs.serviceName == 'sql' || inputs.serviceName == '(all)' }}
    uses: ./.github/workflows/deploy-svc-sql.yml
    secrets: inherit
    with:
      imageTag: ${{ needs.CalculateImageTags.outputs.IMAGE_TAG_SHA }}
      envName: ${{ inputs.envName }}
