name: 🚀 Deploy Single Function
run-name: Deploy Function ${{ inputs.functionName }} to ${{ inputs.envName }}

on:
  workflow_dispatch:
    inputs:
      envName:
        description: "envName:\nNote: Functions are only deployed in shared environments"
        type: string
        required: true
      functionName:
        description: "functionName:\nsingle or comma,separated,list"
        type: string
        required: true

jobs:
  EnsureBuild:
    uses: ./.github/workflows/Build.yml
  CalculateImageTags:
    uses: ./.github/workflows/CalculateImageTags.yml
  CloudFunctionsDeploy:
    needs: [EnsureBuild, CalculateImageTags]
    uses: ./.github/workflows/deploy-svc-cloud-functions.yml
    secrets: inherit
    with:
      imageTag: ${{ needs.CalculateImageTags.outputs.IMAGE_TAG_SHA }}
      envName: ${{ inputs.envName }}
      functionName: ${{ inputs.functionName }}
