name: ⚙️ Get Image Tags

on:
  workflow_call:
    outputs:
      image-tag-sha:
        value: ${{ jobs.GetBuildImage.outputs.IMAGE_TAG_SHA}}
      image-tag-ref:
        value: ${{ jobs.GetBuildImage.outputs.IMAGE_TAG_REF}}

jobs:
  GetBuildImageTags:
    concurrency:
      group: GetBuildImage-${{ github.ref }}
    runs-on: ubuntu-latest
    environment: build
    outputs:
      TARGET_IMAGE: ${{ steps.pullImage.outputs.TARGET_IMAGE }}
    steps:
      - id: pullImage
        run: |
          TARGET_SHA="${{ github.event.pull_request.head.sha || github.ref }}"
          TARGET_REPO="${{ vars.GCP_LOCATION }}-docker.pkg.dev/${{ vars.GCP_PROJECT }}/builds/build"
          IMAGE_SHA="git-${TARGET_SHA}"
          TARGET_IMAGE="${TARGET_REPO}:${TARGET_TAG}"

          echo "TARGET_IMAGE=${TARGET_IMAGE}" >>"$GITHUB_OUTPUT"
