name: Hello

on:
  workflow_dispatch:

  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo "Hello, World!"
