name: ⚙️ Infrastructure Stack Deployment

on:
  workflow_call:
    inputs:
      imageTag:
        type: string
        required: true
      serviceName:
        type: string
        required: true
      envName:
        type: string
        required: true

jobs:
  DeployInfraStack:
    name: Deploy ${{ inputs.serviceName }}-${{ inputs.envName }} (Infrastructure Stack)
    environment: ${{ inputs.envName }}
    runs-on: ubuntu-latest
    concurrency:
      group: DeployInfraStack-${{ inputs.serviceName }}-${{ inputs.envName }}
    steps:
      - uses: "google-github-actions/auth@v2"
        with:
          project_id: "${{ vars.GCP_PROJECT }}"
          credentials_json: "${{ secrets.GCP_PRIVATE_KEY_JSON }}"
      - run: |
          # Deploy Infrastructure Stack: ${{ inputs.serviceName }} in ${{ inputs.envName }}
          gcloud auth configure-docker ${{ vars.GCP_LOCATION }}-docker.pkg.dev --quiet
          # FIXME: needs google creds passed in
          docker run ${{ inputs.imageTag }} \
            pnpm infra ${{ inputs.serviceName }}-${{ inputs.envName }}
