name: Deploy Admin

on:
  workflow_call:
    inputs:
      envName:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      envName:
        required: true
        type: choice
        options:
          - dev
          # - prod

jobs:
  doMigrateSQL:
    runs-on: ubuntu-latest
    concurrency:
      group: migrate-sql-${{ inputs.envName }}
    steps:
      - run: |
          echo "Migrating SQL"
