name: 🔄 On Pull Request
run-name: "Pull request #${{ github.event.pull_request.number }} updated"

on:
  pull_request:

jobs:
  Test:
    uses: ./.github/workflows/UnitTest.yml
# FIXME: add preview-cloudtasks-dev/prod
# FIXME: add preview-cloudsql-dev/prod
