name: On Pull Request

on:
  pull_request:

jobs:
  Build:
    uses: ./.github/workflows/Build.yml
  Test:
    needs: [Build]
    uses: ./.github/workflows/Test.yml
# FIXME: add preview-cloudtasks-dev/prod
# FIXME: add preview-cloudsql-dev/prod
