name: Pulumi Stack Deployment
run-name: Deploy Pulumi stack ${{ inputs.stackName }}

on:
  workflow_call:
    inputs:
      stackName:
        type: string
        required: true

jobs:
  deployCloudFunction:
    runs-on: ubuntu-latest
    concurrency:
      group: stack-${{ inputs.stackName }}
    steps:
      - run: |
          echo "Deploy Pulumi Stack: ${{ inputs.stackName }}"
