name: SQL Migration
run-name: Run SQL Migrations in ${{ inputs.envName }}

on:
  workflow_call:
    inputs:
      envName:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      envName:
        required: true
        type: choice
        options:
          - dev
          # - prod

jobs:
  SqlMigration:
    runs-on: ubuntu-latest
    concurrency:
      group: SqlMigration-${{ inputs.envName }}
    steps:
      - run: |
          echo "Migrating SQL"
