name: SQL Migration

on:
  workflow_call:
    inputs:
      envName:
        required: true
        type: string

jobs:
  SqlMigration:
    name: SqlMigration-${{ inputs.envName }}
    runs-on: ubuntu-latest
    concurrency:
      group: SqlMigration-${{ inputs.envName }}
    steps:
      - run: |
          echo "Migrating SQL"
