name: ⚙️ SQL Migration

on:
  workflow_call:
    inputs:
      imageTag:
        type: string
        required: true
      envName:
        required: true
        type: string

jobs:
  SqlMigration:
    name: Migrate SQL in ${{ inputs.envName }}
    environment: ${{ inputs.envName }}
    runs-on: ubuntu-latest
    concurrency:
      group: SqlMigration-${{ inputs.envName }}
    steps:
      - uses: "google-github-actions/auth@v2"
        with:
          project_id: "${{ vars.GCP_PROJECT }}"
          credentials_json: "${{ secrets.GCP_PRIVATE_KEY_JSON }}"
      - run: |
          # Deploy SQL in ${{ inputs.envName }}
          gcloud auth configure-docker ${{ vars.GCP_LOCATION }}-docker.pkg.dev --quiet
          # FIXME: needs google creds passed in
          docker run ${{ inputs.imageTag }} pnpm sql:migrate ${{ inputs.envName }}
