name: ⚙️ Unit Tests

on:
  workflow_call:
    secrets:
      GCP_PRIVATE_KEY_JSON:

jobs:
  GetBuildImage:
    uses: ./.github/workflows/GetBuildImage.yml
  UnitTests:
    needs: [GetBuildImage]
    environment: build
    concurrency:
      group: UnitTests-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/auth@v2
        with:
          project_id: "${{ vars.GCP_PROJECT }}"
          credentials_json: "${{ secrets.GCP_PRIVATE_KEY_JSON }}"
      - run: |
          # Run unit tests
          docker run --rm ${{ needs.GetBuildImage.outputs.image-tag-sha }} pnpm test
