name: ⚙️ Unit Tests

on:
  workflow_call:

jobs:
  EnsureBuild:
    uses: ./.github/workflows/Build.yml
    secrets: inherit
    with:
      pull: true
  UnitTests:
    needs: [EnsureBuild]
    environment: build
    concurrency:
      group: UnitTests-${{ github.head_ref || github.ref }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
      - run: |
          # Run unit tests
          docker run ${{ needs.EnsureBuild.outputs.image-tag-sha }} pnpm test
