name: ⚙️ Unit Tests

on:
  workflow_call:
    secrets:
      GCP_PRIVATE_KEY_JSON:

jobs:
  UnitTests:
    environment: build
    concurrency:
      group: UnitTests-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/auth@v2
        with:
          project_id: "${{ vars.GCP_PROJECT }}"
          credentials_json: "${{ secrets.GCP_PRIVATE_KEY_JSON }}"
      - id: getBuildImage
        uses: ./.github/workflows/GetBuildImage.yml
      - run: |
          # Run unit tests
          docker run --rm ${{ steps.getBuildImage.outputs.TARGET_IMAGE }} pnpm test
