name: ⚙️ Unit Tests

on:
  workflow_call:
    secrets:
      GCP_PRIVATE_KEY_JSON:

jobs:
  UnitTests:
    environment: build
    concurrency:
      group: UnitTests-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - uses: "google-github-actions/auth@v2"
        with:
          project_id: "${{ vars.GCP_PROJECT }}"
          credentials_json: "${{ secrets.GCP_PRIVATE_KEY_JSON }}"
      - run: |
          # Run unit tests
          TARGET_IMAGE="${{ vars.GCP_LOCATION }}-docker.pkg.dev/${{ vars.GCP_PROJECT }}/builds/build:git-${{ github.sha }}"
          gcloud auth configure-docker ${{ vars.GCP_LOCATION }}-docker.pkg.dev
          docker run --rm ${TARGET_IMAGE} pnpm test
