name: _Unit Tests

on:
  workflow_call:

jobs:
  UnitTests:
    name: Unit test ${{ github.ref }}@${{ github.sha }}
    concurrency:
      group: UnitTests-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running unit tests"
      - run: echo "Pushing statistics"
