name: Unit Tests
run-name: "[Tests] ${{ github.ref_name }} @ ${{ github.sha }}"

on:
  workflow_call:

jobs:
  UnitTests:
    concurrency:
      group: UnitTests-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running unit tests"
      - run: echo "Pushing statistics"
