name: ⚙️ Unit Tests

on:
  workflow_call:

# Both of these jobs have the same concurrency group as Build. This ensures
# that the UnitTests job is queued after the push is built.
# (Build -> EnsureBuild), UnitTests
# (EnsureBuild -> Build), UnitTests
jobs:
  EnsureBuild:
    concurrency:
      group: Build-${{ github.head_ref || github.ref }}
    uses: ./.github/workflows/CalculateImageTags.yml
  UnitTests:
    needs: [EnsureBuild]
    environment: build
    concurrency:
      group: Build-${{ github.head_ref || github.ref }}
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/auth@v2
        with:
          project_id: "${{ vars.GCP_PROJECT }}"
          credentials_json: "${{ secrets.GCP_PRIVATE_KEY_JSON }}"
      - run: |
          # Run unit tests
          gcloud auth configure-docker ${{ vars.GCP_LOCATION }}-docker.pkg.dev --quiet
          docker run ${{ needs.EnsureBuild.outputs.image-tag-sha }} pnpm test
