name: Unit Tests

on:
  workflow_call:

jobs:
  UnitTests:
    name: UnitTests-${{ github.ref }}
    concurrency:
      group: UnitTests-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running unit tests"
      - run: echo "Pushing statistics"
